### ISSUE TITLE
这个报错了 怎么办啊

### ISSUE THREAD

**Issue by sobimask** [lemotg/PyApi#1]
![image](https://user-images.githubusercontent.com/51392055/65480415-f318f980-dec3-11e9-83bd-9596baeeb57b.png)

**Comment by DDDDanny** [comment]
这个是读取config.ini配置文件报错，你在config目录下添加配置文件即可。（配置文件的Key可以根据你的需求进行更改，同时需要修改get_value.py的Key，这样才能正常读取配置文件）
